variable:
  profiles: dev

# web port
server:
  port: 9080
  servlet:
    context-path: /

#spring:
#  datasource:
#    dynamic:
#      primary: mini_app
#      strict: false # 严格匹配数据源,默认false. true未匹配到指定数据源时抛异常, false使用默认数据源
#      datasource:
#        mini_app:
#          url: jdbc:mysql://192.168.50.130:3306/mini_app?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#          username: miniapp
#          password: Ma+911105
#          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
#        slave:
#          url: jdbc:mysql://192.168.50.130:3306/miniapp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#          username: miniapp
#          password: Ma+911105
#          driver-class-name: com.mysql.cj.jdbc.Driver