server:
  port: 9080

# database configuration
spring:
  profiles:
    active: dev
  datasource:
    dynamic:
      primary: mini_app
      datasource:
        mini_app:
          url: jdbc:mysql://49.235.114.239:3306/mini_app?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
          username: guanyu
          password: Tcstanderds2+
          driver-class-name: com.mysql.jdbc.Driver
        web_tools:
          url: jdbc:mysql://49.235.114.239:3306/web_tools?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
          username: guanyu
          password: Tcstanderds2+
          driver-class-name: com.mysql.jdbc.Driver

# mybatis plus enable sql print
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl